### ISSUE TITLE
output is inverted in certain input formats

### ISSUE THREAD

**Issue by bertsky** [qurator-spk/sbb_binarization#33] opened 2021-10-23 22:22 UTC
I sometimes get output which looks like this:

![OCR-D-SEG-PAGE-BIN_Ratsbuecher_O_10_0237 IMG-BIN](https://user-images.githubusercontent.com/38561704/138573319-087c1b46-aaf8-4404-9134-8a08d84711fe.png)

The input image for this was a PNG (which someone seems to have converted somehow from an original JPEG):

![Ratsbuecher_O_10_0237](https://user-images.githubusercontent.com/38561704/138573356-10784ea8-6845-4f32-bc18-7a7c4a19ce03.png)

(That's from [this GT](https://zenodo.org/record/5153263#.YV7a53VfjCM) BTW.)

**Comment by cneud** [comment] 2022-04-26 16:34
I also tried out current master with the example images above, but all outputs were fine and as expected, I cannot reproduce?

**Comment by cneud** [comment] 2022-08-26 12:29
@bertsky Since neither @vahidrezanezhad nor I can reproduce, I will close this, but feel free to reopen if you encounter this again with the current code.

**Closed by cneud** 2022-08-26 12:29 UTC
Labels: bug

**Comment by bertsky** [comment] 2022-10-10 18:30
Confirming this went away with 0.0.10. (Last tried 0.0.8) 

Thanks for your feedback.
